import { ProductItem } from "./types";

export const chessCollections: ProductItem[] = [
  // ICEY OBSIDIAN SERIES
  {
    id: "icey-obsedion",
    href: "/products/icey-obsedion-chess",
    title: "Icey Obsedian Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-obsedion/image1.png",
    imgDesktop: "/assets/chess-collections/icey-obsedion/image1.png",
    images: [
      "/assets/chess-collections/icey-obsedion/image2.JPG",
      "/assets/chess-collections/icey-obsedion/image3.JPG",
      "/assets/chess-collections/icey-obsedion/image4.JPG",
      "/assets/chess-collections/icey-obsedion/image5.JPG",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  // ICEY GLACIER SERIES
  {
    id: "icey-glacier",
    href: "/products/icey-glacier-chess",
    title: "Icey Glacier Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-glacier/image1.png",
    imgDesktop: "/assets/chess-collections/icey-glacier/image1.png",
    images: [
      "/assets/chess-collections/icey-glacier/image2.png",
      "/assets/chess-collections/icey-glacier/image3.JPG",
      "/assets/chess-collections/icey-glacier/image4.JPG",
    ],
    price: "3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  // ICEY EMERALD SERIES
  {
    id: "icey-emerald",
    href: "/products/icey-emerald-chess",
    title: "Icey Emerald Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-emerald/main.png",
    imgDesktop: "/assets/chess-collections/icey-emerald/main.png",
    images: [
      "/assets/chess-collections/icey-emerald/preview1.JPG",
      "/assets/chess-collections/icey-emerald/preview2.JPG",
      "/assets/chess-collections/icey-emerald/preview3.JPG",
      "/assets/chess-collections/icey-emerald/preview4.JPG",
      "/assets/chess-collections/icey-emerald/preview5.JPG",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  //ICEY HELIOS SERIES
  {
    id: "icey-helios",
    href: "/products/icey-helios-chess",
    title: "Icey Helios Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-helios/main.png",
    imgDesktop: "/assets/chess-collections/icey-helios/main.png",
    images: [
      "/assets/chess-collections/icey-helios/preview1.JPG",
      "/assets/chess-collections/icey-helios/preview2.JPG",
      "/assets/chess-collections/icey-helios/preview3.JPG",
      "/assets/chess-collections/icey-helios/preview4.JPG",
      "/assets/chess-collections/icey-helios/preview5.JPG",
      "/assets/chess-collections/icey-helios/preview6.JPG",
      "/assets/chess-collections/icey-helios/preview7.JPG",
      "/assets/chess-collections/icey-helios/preview8.JPG",
      "/assets/chess-collections/icey-helios/preview9.JPG",
      "/assets/chess-collections/icey-helios/preview10.JPG",
      "/assets/chess-collections/icey-helios/preview11.JPG",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  // ICEY ROSE SERIES
  {
    id: "icey-rose",
    href: "/products/icey-rose-chess",
    title: "Icey Rose Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-rose/main.JPG",
    imgDesktop: "/assets/chess-collections/icey-rose/main.JPG",
    images: [
      "/assets/chess-collections/icey-rose/preview1.jpg",
      "/assets/chess-collections/icey-rose/preview2.jpg",
      "/assets/chess-collections/icey-rose/preview3.jpg",
      "/assets/chess-collections/icey-rose/preview4.jpg",
      "/assets/chess-collections/icey-rose/preview5.jpg",
      "/assets/chess-collections/icey-rose/preview6.jpg",
      "/assets/chess-collections/icey-rose/preview7.jpg",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  //SAPPHIRE SERIES
  {
    id: "sapphire",
    href: "/products/sapphire-chess",
    title: "Sapphire Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/sapphire/main.png",
    imgDesktop: "/assets/chess-collections/sapphire/main.png",
    images: [
      "/assets/chess-collections/sapphire/preview1.png",
      "/assets/chess-collections/sapphire/preview2.JPG",
      "/assets/chess-collections/sapphire/preview3.jpg",
      "/assets/chess-collections/sapphire/preview4.jpg",
    ],
    price: "₹7999",
    priceOriginal: "₹8499",
    discountText: "5% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "2.5KG - 4 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "14’’ x 14’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "2’’ – 3’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  // JADE SERIES
  {
    id: "jade",
    href: "/products/jade-chess",
    title: "Jade Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/jade/main.JPG",
    imgDesktop: "/assets/chess-collections/jade/main.JPG",
    images: [
      "/assets/chess-collections/jade/preview1.jpg",
      "/assets/chess-collections/jade/preview2.jpg",
    ],
    price: "₹7999",
    priceOriginal: "₹8499",
    discountText: "5% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "2.5KG - 4 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "14’’ x 14’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "2’’ – 3’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  // ICEY RUBY SERIES
  {
    id: "icey-ruby",
    href: "/products/icey-ruby-chess",
    title: "Icey Ruby Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-ruby/main.png",
    imgDesktop: "/assets/chess-collections/icey-ruby/main.png",
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  //ICY WHITE WALKER SERIES
  {
    id: "icey-white-walker",
    href: "/products/icey-white-walker-chess",
    title: "Icey White Walker Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-white-walker/main.png",
    imgDesktop: "/assets/chess-collections/icey-white-walker/main.png",
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: Assorted Chess Men Included (1 set Transparent Resin, 1 set Matching Board Tone). For Color Change Requests, Please Contact Us",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  //icey-amethyst-series
  {
    id: "icey-amethyst",
    href: "/products/icey-amethyst-chess",
    title: "Icey Amethyst Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-amethyst/main.png",
    imgDesktop: "/assets/chess-collections/icey-amethyst/main.png",
    images: [
      "/assets/chess-collections/icey-amethyst/preview1.JPG",
      "/assets/chess-collections/icey-amethyst/preview2.JPG",
      "/assets/chess-collections/icey-amethyst/preview3.JPG",
      "/assets/chess-collections/icey-amethyst/preview4.png",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "1.8KG - 3 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "11’’ x 11’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "3/4’’ – 1 1/2’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
  //solid-black-series
  {
    id: "solid-black",
    href: "/products/solid-black-chess",
    title: "Solid Black Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/solid-black/main.png",
    imgDesktop: "/assets/chess-collections/solid-black/main.png",
    images: [
      "/assets/chess-collections/solid-black/preview1.jpg",
      "/assets/chess-collections/solid-black/preview2.jpg",
      "/assets/chess-collections/solid-black/preview3.jpg",
      "/assets/chess-collections/solid-black/preview4.jpg",
    ],
    price: "₹7999",
    priceOriginal: "₹8499",
    discountText: "5% Off",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood Chess Board with Crystal-clear Epoxy Resin Finish",
      "Items": "Complete Chess Set (Board + Chess Pieces + Assembly Accessories)",
      "Color": "Chess Pieces: 1 set Transparent Resin, 1 set Matching Board Tone",
      "Design/Style": "Luxury Epoxy Resin Chess Board, Modern Industrial, Handcrafted Strategy Set",
      "Special Metal Decorated Chessmen": "1 Premium Metal Chessmen Set Matching Board + 1 Plain Set (Optional Upgrade 999/-)",
      "Weight": "2.5KG - 4 KG (Varies by Chess Board Design)",
      "Usage": "Chess Play, Home Decor, Office Display, Strategy Practice, Gift Item",
      "Product Size": "14’’ x 14’’ (Standard Compact Chess Board Size)",
      "THICKNESS": "2’’ – 3’’ (Solid Chess Board Build)",
      "Manufacturing Process": "Handcrafted Chess Board & Pieces",
      "Manufacturing": "Made in India with High-Quality Chess Craftsmanship",
      "Delivery": "PAN India Delivery Available",
      "Brand": "Royality Resin Chess Collection"
    }
  },
];