export const chessCollections = [
  // ICEY OBSIDIAN SERIES
  {
    id: "icey-obsedion",
    href: "/products/icey-obsedion-chess",
    title: "Icey Obsedian Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-obsedion/image1.png",
    imgDesktop: "/assets/chess-collections/icey-obsedion/image1.png",
    images: [
      "/assets/chess-collections/icey-obsedion/image2.JPG",
      "/assets/chess-collections/icey-obsedion/image3.JPG",
      "/assets/chess-collections/icey-obsedion/image4.JPG",
      "/assets/chess-collections/icey-obsedion/image5.JPG",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
  },
  // ICEY GLACIER SERIES
  {
    id: "icey-glacier",
    href: "/products/icey-glacier-chess",
    title: "Icey Glacier Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-glacier/image1.png",
    imgDesktop: "/assets/chess-collections/icey-glacier/image1.png",
    images: [
      "/assets/chess-collections/icey-glacier/image2.png",
      "/assets/chess-collections/icey-glacier/image3.JPG",
      "/assets/chess-collections/icey-glacier/image4.JPG",
    ],
    price: "3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
  },
  // ICEY EMERALD SERIES
  {
    id: "icey-emerald",
    href: "/products/icey-emerald-chess",
    title: "Icey Emerald Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-emerald/main.png",
    imgDesktop: "/assets/chess-collections/icey-emerald/main.png",
    images: [
      "/assets/chess-collections/icey-emerald/preview1.JPG",
      "/assets/chess-collections/icey-emerald/preview2.JPG",
      "/assets/chess-collections/icey-emerald/preview3.JPG",
      "/assets/chess-collections/icey-emerald/preview4.JPG",
      "/assets/chess-collections/icey-emerald/preview5.JPG",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
  },
  //ICEY HELIOS SERIES
  {
    id: "icey-helios",
    href: "/products/icey-helios-chess",
    title: "Icey Helios Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-helios/main.png",
    imgDesktop: "/assets/chess-collections/icey-helios/main.png",
    images: [
      "/assets/chess-collections/icey-helios/preview1.JPG",
      "/assets/chess-collections/icey-helios/preview2.JPG",
      "/assets/chess-collections/icey-helios/preview3.JPG",
      "/assets/chess-collections/icey-helios/preview4.JPG",
      "/assets/chess-collections/icey-helios/preview5.JPG",
      "/assets/chess-collections/icey-helios/preview6.JPG",
      "/assets/chess-collections/icey-helios/preview7.JPG",
      "/assets/chess-collections/icey-helios/preview8.JPG",
      "/assets/chess-collections/icey-helios/preview9.JPG",
      "/assets/chess-collections/icey-helios/preview10.JPG",
      "/assets/chess-collections/icey-helios/preview11.JPG",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
  },
  // ICEY ROSE SERIES
  {
    id: "icey-rose",
    href: "/products/icey-rose-chess",
    title: "Icey Rose Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/icey-rose/main.JPG",
    imgDesktop: "/assets/chess-collections/icey-rose/main.JPG",
    images: [
      "/assets/chess-collections/icey-rose/preview1.jpg",
      "/assets/chess-collections/icey-rose/preview2.jpg",
      "/assets/chess-collections/icey-rose/preview3.jpg",
      "/assets/chess-collections/icey-rose/preview4.jpg",
      "/assets/chess-collections/icey-rose/preview5.jpg",
      "/assets/chess-collections/icey-rose/preview6.jpg",
      "/assets/chess-collections/icey-rose/preview7.jpg",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
  },
  //SAPPHIRE SERIES
  {
    id: "sapphire",
    href: "/products/sapphire-chess",
    title: "Sapphire Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/sapphire/main.png",
    imgDesktop: "/assets/chess-collections/sapphire/main.png",
    images: [
      "/assets/chess-collections/sapphire/preview1.png",
      "/assets/chess-collections/sapphire/preview2.JPG",
      "/assets/chess-collections/sapphire/preview3.jpg",
      "/assets/chess-collections/sapphire/preview4.jpg",
    ],
    price: "₹3999",
    priceOriginal: "₹4499",
    discountText: "11% Off",
  },
];