export const chessCollections = [
  // BLACK ICE SERIES
  {
    id: "black-ice-1",
    href: "/products/black-ice-cracked",
    title: "Black Ice Cracked Resin Chess Set",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-ice/image1.png",
    imgDesktop: "/assets/chess-collections/black-ice/image1.png",
    price: "₹8,500",
    priceOriginal: "₹12,000",
    discountText: "29% Off",
  },
  {
    id: "black-ice-2",
    href: "/products/black-ice-obsidian",
    title: "Black Ice Obsidian Edition",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-ice/image2.JPG",
    imgDesktop: "/assets/chess-collections/black-ice/image2.JPG",
    price: "₹8,500",
    priceOriginal: "₹12,000",
    discountText: "29% Off",
  },
  {
    id: "black-ice-3",
    href: "/products/black-ice-crystal",
    title: "Black Ice Crystal Board",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-ice/image3.JPG",
    imgDesktop: "/assets/chess-collections/black-ice/image3.JPG",
    price: "₹8,500",
    priceOriginal: "₹12,000",
    discountText: "29% Off",
  },
  {
    id: "black-ice-4",
    href: "/products/black-ice-monolith",
    title: "Black Ice Monolith Set",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-ice/image4.JPG",
    imgDesktop: "/assets/chess-collections/black-ice/image4.JPG",
    price: "₹8,500",
    priceOriginal: "₹12,000",
    discountText: "29% Off",
  },
  {
    id: "black-ice-5",
    href: "/products/black-ice-phantom",
    title: "Black Ice Phantom Series",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-ice/image5.JPG",
    imgDesktop: "/assets/chess-collections/black-ice/image5.JPG",
    price: "₹8,500",
    priceOriginal: "₹12,000",
    discountText: "29% Off",
  },

  // BLACK SOLID SERIES
  {
    id: "black-solid-1",
    href: "/products/black-solid-classic",
    title: "Black Solid Classic Resin Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-solid/image1.png",
    imgDesktop: "/assets/chess-collections/black-solid/image1.png",
    price: "₹7,500",
    priceOriginal: "₹10,000",
    discountText: "25% Off",
  },
  {
    id: "black-solid-2",
    href: "/products/black-solid-matte",
    title: "Black Solid Matte Finish",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-solid/image2.png",
    imgDesktop: "/assets/chess-collections/black-solid/image2.png",
    price: "₹7,500",
    priceOriginal: "₹10,000",
    discountText: "25% Off",
  },
  {
    id: "black-solid-3",
    href: "/products/black-solid-onyx",
    title: "Black Solid Onyx Edition",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-solid/image3.png",
    imgDesktop: "/assets/chess-collections/black-solid/image3.png",
    price: "₹7,500",
    priceOriginal: "₹10,000",
    discountText: "25% Off",
  },
  {
    id: "black-solid-4",
    href: "/products/black-solid-noir",
    title: "Black Solid Noir Series",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-solid/image4.jpg",
    imgDesktop: "/assets/chess-collections/black-solid/image4.jpg",
    price: "₹7,500",
    priceOriginal: "₹10,000",
    discountText: "25% Off",
  },
  {
    id: "black-solid-5",
    href: "/products/black-solid-vanta",
    title: "Black Solid Vanta Board",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-solid/image5.jpg",
    imgDesktop: "/assets/chess-collections/black-solid/image5.jpg",
    price: "₹7,500",
    priceOriginal: "₹10,000",
    discountText: "25% Off",
  },
  {
    id: "black-solid-6",
    href: "/products/black-solid-eclipse",
    title: "Black Solid Eclipse Edition",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/black-solid/image6.jpg",
    imgDesktop: "/assets/chess-collections/black-solid/image6.jpg",
    price: "₹7,500",
    priceOriginal: "₹10,000",
    discountText: "25% Off",
  },

  // BLUE ICE SERIES
  {
    id: "blue-ice-1",
    href: "/products/blue-ice-arctic",
    title: "Blue Ice Arctic Resin Chess",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/blue-ice/image1.png",
    imgDesktop: "/assets/chess-collections/blue-ice/image1.png",
    price: "₹9,000",
    priceOriginal: "₹13,000",
    discountText: "30% Off",
  },
  {
    id: "blue-ice-2",
    href: "/products/blue-ice-glacier",
    title: "Blue Ice Glacier Edition",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/blue-ice/image2.png",
    imgDesktop: "/assets/chess-collections/blue-ice/image2.png",
    price: "₹9,000",
    priceOriginal: "₹13,000",
    discountText: "30% Off",
  },
  {
    id: "blue-ice-3",
    href: "/products/blue-ice-deep-sea",
    title: "Blue Ice Deep Sea Board",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/blue-ice/image3.JPG",
    imgDesktop: "/assets/chess-collections/blue-ice/image3.JPG",
    price: "₹9,000",
    priceOriginal: "₹13,000",
    discountText: "30% Off",
  },
  {
    id: "blue-ice-4",
    href: "/products/blue-ice-frostbite",
    title: "Blue Ice Frostbite Series",
    categoryName: "Chess Collections",
    categoryHref: "/collections/chess-collections",
    img: "/assets/chess-collections/blue-ice/image4.JPG",
    imgDesktop: "/assets/chess-collections/blue-ice/image4.JPG",
    price: "₹9,000",
    priceOriginal: "₹13,000",
    discountText: "30% Off",
  },
];