export const diningCollections = [
  // ICE CRACK SERIES
  {
    id: "ice-crack-1",
    href: "/products/ice-crack-modern",
    title: "Ice Crack Modern Dining Table",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/ice-crack/image1.png",
    imgDesktop: "/assets/dining-tables/ice-crack/image1.png",
    price: "₹65,000",
    priceOriginal: "₹85,000",
    discountText: "23% Off",
  },
  {
    id: "ice-crack-2",
    href: "/products/ice-crack-fluid",
    title: "Ice Crack Fluid Texture Edition",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/ice-crack/image2.png",
    imgDesktop: "/assets/dining-tables/ice-crack/image2.png",
    price: "₹65,000",
    priceOriginal: "₹85,000",
    discountText: "23% Off",
  },

  // LAVA SERIES
  {
    id: "lava-1",
    href: "/products/lava-molten",
    title: "Lava Molten Resin Dining Table",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/lava/image1.png",
    imgDesktop: "/assets/dining-tables/lava/image1.png",
    price: "₹72,000",
    priceOriginal: "₹95,000",
    discountText: "24% Off",
  },

  // SEA SHELL SERIES
  {
    id: "sea-shell-1",
    href: "/products/sea-shell-pearl",
    title: "Sea Shell Pearl & Teak Table",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/sea-shell/image1.png",
    imgDesktop: "/assets/dining-tables/sea-shell/image1.png",
    price: "₹85,000",
    priceOriginal: "₹1,10,000",
    discountText: "22% Off",
  },
  {
    id: "sea-shell-2",
    href: "/products/sea-shell-ocean-floor",
    title: "Sea Shell Ocean Floor Design",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/sea-shell/image2.png",
    imgDesktop: "/assets/dining-tables/sea-shell/image2.png",
    price: "₹85,000",
    priceOriginal: "₹1,10,000",
    discountText: "22% Off",
  },
  {
    id: "sea-shell-3",
    href: "/products/sea-shell-coastal",
    title: "Sea Shell Coastal Heritage Piece",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/sea-shell/image3.png",
    imgDesktop: "/assets/dining-tables/sea-shell/image3.png",
    price: "₹85,000",
    priceOriginal: "₹1,10,000",
    discountText: "22% Off",
  },
  {
    id: "sea-shell-4",
    href: "/products/sea-shell-deep-reef",
    title: "Sea Shell Deep Reef Edition",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/sea-shell/image4.JPG",
    imgDesktop: "/assets/dining-tables/sea-shell/image4.JPG",
    price: "₹85,000",
    priceOriginal: "₹1,10,000",
    discountText: "22% Off",
  },

  // SPICE SERIES
  {
    id: "spice-1",
    href: "/products/spice-heritage",
    title: "Spice Heritage Prosperity Table",
    categoryName: "Dining Tables",
    categoryHref: "/collections/dining-tables",
    img: "/assets/dining-tables/spice/image1.png",
    imgDesktop: "/assets/dining-tables/spice/image1.png",
    price: "₹58,000",
    priceOriginal: "₹75,000",
    discountText: "22% Off",
  },
];