import { ProductItem } from "./types";

export const sideCoffeeProducts: ProductItem[] = [
  // ABSTRACT
  {
    id: "abstract-1",
    href: "/products/abstract-1",
    title: "Abstract Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/abstract/image1.png",
    imgDesktop: "/assets/side-coffee-table/abstract/image1.png",
    price: "₹12,999",
    Specifications: {
      "Wood/Material": "Live-edge HDF/MDF Boards with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (HDF/MDF Boards + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’ x 36’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },
  {
    id: "abstract-2",
    href: "/products/abstract-2",
    title: "Abstract Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/abstract/image3.png",
    imgDesktop: "/assets/side-coffee-table/abstract/image3.png",
    price: "₹12,999",
    Specifications: {
      "Wood/Material": "Live-edge HDF/MDF Boards with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (HDF/MDF Boards + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’ x 36’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },
  {
    id: "abstract-3",
    href: "/products/abstract-3",
    title: "Abstract Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/abstract/image4.png",
    imgDesktop: "/assets/side-coffee-table/abstract/image4.png",
    price: "₹12,999",
    Specifications: {
      "Wood/Material": "Live-edge HDF/MDF Boards with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (HDF/MDF Boards + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’ x 36’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },

  // COFFEE
  {
    id: "coffee-bean-table",
    href: "/products/coffee-bean-table",
    title: "Coffee Bean Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/coffee/image1.png",
    imgDesktop: "/assets/side-coffee-table/coffee/image1.png",
    images: [
      "/assets/side-coffee-table/coffee/image2.JPG",
      "/assets/side-coffee-table/coffee/image3.JPG",
    ],
    price: "₹22,999",
    Specifications: {
      "Wood/Material": "Live-edge Teak Wood with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (Teak Wood + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’x36’’x30’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },
  // GEODE
  {
    id: "geode-1",
    href: "/products/geode-1",
    title: "Geode Resin Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/geode/image4.png",
    imgDesktop: "/assets/side-coffee-table/geode/image4.png",
    price: "₹18,999",
    images: [
      "/assets/side-coffee-table/geode/image2.png",
      "/assets/side-coffee-table/geode/image1.png",
    ],
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (Acacia Wood + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’x40’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },

  {
    id: "geode-2",
    href: "/products/geode-2",
    title: "Geode Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/geode/image3.png",
    imgDesktop: "/assets/side-coffee-table/geode/image3.png",
    price: "₹15,999",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Thickness": "1-2 inches",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (Acacia Wood + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’x36’’x30’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },

  // MOON
  {
    id: "moon-1",
    href: "/products/moon-1",
    title: "Moon Resin Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/moon/image1.png",
    imgDesktop: "/assets/side-coffee-table/moon/image1.png",
    images: [
      "/assets/side-coffee-table/moon/image2.png",
      "/assets/side-coffee-table/moon/image3.jpg",
      "/assets/side-coffee-table/moon/image4.png",
      "/assets/side-coffee-table/moon/image5.png",
      "/assets/side-coffee-table/moon/image6.png",
    ],
    price: "₹11,999",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood with Crystal-clear Epoxy Resin",
      "Items": "Only Table with Assembly Accessories",
      "Thickness": "1 1/2 - 2 inches Request for additional thickness Contact Us",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (Acacia Wood + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’x36’’x30’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },

  // MULTICOLOR SEA
  {
    id: "sea-1",
    href: "/products/sea-1",
    title: "Multicolor Sea Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/multicolor-sea/image1.png",
    imgDesktop: "/assets/side-coffee-table/multicolor-sea/image1.png",
    price: "₹15,500",
    priceOriginal: "₹21,000",
    discountText: "26% Off",
  },

  // TURQUOISE
  {
    id: "turquoise-1",
    href: "/products/turquoise-1",
    title: "Turquoise Resin Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/turquoise/image1.png",
    imgDesktop: "/assets/side-coffee-table/turquoise/image1.png",
    price: "₹15,000",
    priceOriginal: "₹20,000",
    discountText: "25% Off",
  },

  // FLOWER
  {
    id: "flower-1",
    href: "/products/flower-1",
    title: "Flower Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/flower/image1.png",
    imgDesktop: "/assets/side-coffee-table/flower/image1.png",
    price: "₹21,000",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood with Crystal-clear Epoxy Resin",
      "Table top thickness": "1-2 inches",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (Acacia Wood + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "48’’x36’’x30’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },
  {
    id: "rose-table",
    href: "/products/rose-table",
    title: "Rose Table",
    categoryName: "Side & Coffee Tables",
    categoryHref: "/collections/side-coffee-tables",
    img: "/assets/side-coffee-table/flower/image.png",
    imgDesktop: "/assets/side-coffee-table/flower/image.png",
    price: "₹9,999",
    Specifications: {
      "Wood/Material": "Live-edge Acacia Wood with Crystal-clear Epoxy Resin",
      "Table top thickness": "2-3 inches",
      "Items": "Only Table with Assembly Accessories",
      "Color": "Natural Wood Tone with Transparent Epoxy (Customizable)",
      "Design/Style": "Live-edge Epoxy Resin Table, Modern Industrial, Handcrafted",
      "Weight": "Varies (Acacia Wood + Metal Legs)",
      "Usage": "Home, Office, Studio, Dining Table, Decorative Table",
      "Product Size": "36’’ diameter total height 18’’-20’’",
      "Manufacturing Process": "Handcrafted",
      "Base Type": "U-frame Powder-coated Metal Legs",
      "Manufacturing": "Made in the India with high-quality materials",
      "Delivery": "PAN India Delivery",
      "Brand": "Royality Resin"
    },
  },
];